- .github/workflows/python-publish.yaml
Fix problem in python-publish.yaml
> Modify workflow

- .gitignore
- pyatlan/cache/custom_metadata_cache.py
- pyatlan/client/atlan.py
- pyatlan/client/constants.py
- pyatlan/generator/templates/entity.jinja2
- pyatlan/model/assets.py
- pyatlan/model/core.py
- pyatlan/model/structs.py
- tests/integration/custom_metadata_test.py
- tests/unit/test_model.py
- Renamed get_business_attributes method get_custom_metadata in Referenceable.Attributes
- Renamed set_business_attributes method set_custom_metadata in Referenceable.Attributes
- Renamed BusinessAttributes to CustomMetadata
- Add parameter overwrite_custom_metadata to AtlanClient.upsert
- Add get_custom_metadata to CustomMetadataCache
- Update create functions
> Made changes to updating custom meta data

- pyatlan/client/atlan.py
https://linear.app/atlanproduct/issue/ACTIV-571/check-json-decoding
> Fix problem handling response during 500 error

- pyatlan/client/atlan.py
- pyatlan/generator/templates/imports.jinja2
- pyatlan/generator/templates/methods/asset/s3_object.jinja2
- pyatlan/generator/templates/methods/attribute/s3_object.jinja2
- pyatlan/model/assets.py
- pyatlan/model/enums.py
- pyatlan/model/search.py
- pyatlan/model/structs.py
- tests/integration/admin_test.py
- tests/integration/s3_asset_test.py
- tests/integration/test_index_search.py
- tests/unit/model/s3object_test.py
- tests/unit/test_model.py
- tests/unit/test_search_model.py
And adds functionality:
- Bulk delete
- Restore
- Search by certificate
- Activate / deactivate users
- Search by any of multiple types
(Also regenerates model to include latest assets and structs)
> Enhancements + removes user deletion functionality

- .github/workflows/container-test.yaml
Ref : https://github.com/atlanhq/atlan-python/actions/runs/6749769822/job/18350816895
> Test-Workflow : Add write perms for pushing images into ghcr

- pyatlan/client/atlan.py
> DVX-6 Modify so that retry doesn't throw and it's on exception on retry timeout

- pyatlan/client/constants.py
- pyatlan/client/workflow.py
- pyatlan/errors.py
- pyatlan/model/enums.py
- pyatlan/model/packages/base/crawler.py
- pyatlan/model/packages/base/package.py
- pyatlan/model/packages/confluent_kafka_crawler.py
- pyatlan/model/packages/crawler.py
- pyatlan/model/packages/dbt_crawler.py
- pyatlan/model/packages/glue_crawler.py
- pyatlan/model/packages/package.py
- pyatlan/model/packages/powerbi_crawler.py
- pyatlan/model/packages/snowflake_crawler.py
- pyatlan/model/packages/tableau_crawler.py
- pyatlan/utils.py
- tests/unit/data/package_requests/confluent_kafka_direct.json
- tests/unit/data/package_requests/dbt_cloud.json
- tests/unit/data/package_requests/dbt_core.json
- tests/unit/data/package_requests/glue_iam_user.json
- tests/unit/data/package_requests/powerbi_delegated_user.json
- tests/unit/data/package_requests/powerbi_service_principal.json
- tests/unit/data/package_requests/snowflake_basic.json
- tests/unit/data/package_requests/snowflake_keypair.json
- tests/unit/data/package_requests/tableau_access_token.json
- tests/unit/data/package_requests/tableau_basic.json
- tests/unit/test_client.py
- tests/unit/test_packages.py
- tests/unit/test_workflow_client.py
**Need to add support for following packages:**
**Other tasks:**
```py
from pyatlan.model.packages.snowflake_crawler import SnowflakeCrawler
crawler = (
SnowflakeCrawler(
connection_name="<connection-name>",
admin_roles=[RoleCache.get_id_for_name("$admin")],
admin_groups=None,
admin_users=None,
)
.basic_auth(
username="<username>",
password="<password>",
role="<role>",
warehouse="<warehouse>",
)
.information_schema(hostname="<hostname>")
.include(assets={<assets>})
.lineage(True)
.tags(False)
.to_workflow()
)
print(client.workflow.run(crawler))
```
> DVX-118: Add support for workflow packages

- pyatlan/client/admin.py
- pyatlan/client/asset.py
- pyatlan/client/atlan.py
- pyatlan/client/audit.py
- pyatlan/client/credential.py
- pyatlan/client/group.py
- pyatlan/client/role.py
- pyatlan/client/search_log.py
- pyatlan/client/token.py
- pyatlan/client/typedef.py
- pyatlan/client/user.py
- pyatlan/client/workflow.py
- pyatlan/model/assets/asset00.py
- pyatlan/model/packages/base/package.py
- tests/unit/constants.py
- tests/unit/test_client.py
- tests/unit/test_workflow_client.py
**Current limitation:** [pydantic/pydantic/issues/2901](https://github.com/pydantic/pydantic/issues/2901)
I think we have encountered this in the past: [atlanhq/atlan-python/pull/88#discussion_r1260892704](https://github.com/atlanhq/atlan-python/pull/88#discussion_r1260892704)
> DVX-68 Adds type checking to AtlanClient save and other methods

- pyatlan/pkg/models.py
- pyatlan/pkg/widgets.py
- Change default S3 file in package toolkit
- Make sure generated file name doesn't contain special characters
> Fix DVX-189 and DVX-192

- pyatlan/client/constants.py
- pyatlan/client/credential.py
- pyatlan/client/workflow.py
- pyatlan/model/packages/base/crawler.py
- pyatlan/model/workflow.py
- tests/unit/test_workflow_client.py
```py
result = client.workflow.find_by_type(WorkflowPackage.SNOWFLAKE)[0]
workflow_task = result.source.spec.templates[0].dag.tasks[0]
workflow_params = workflow_task.arguments.parameters
for nv in workflow_params:
if nv.name == "enable-lineage":
nv.value = True
response = client.workflow.update(workflow=result.to_workflow())
print(response)
```
> DVX-53: Adds workflow `update` method

- docs/requirements.txt
Fixes : https://github.com/atlanhq/atlan-python/actions/runs/7934627626/job/21666006187
> Update docs requirements

- pyatlan/model/search.py
- tests/unit/test_search_model.py
> Fixes `to_dict` method handling of range query for `datetime` attributes

- pyatlan/model/packages/__init__.py
- pyatlan/model/packages/confluent_kafka_crawler.py
- pyatlan/model/packages/dbt_crawler.py
- pyatlan/model/packages/glue_crawler.py
- pyatlan/model/packages/powerbi_crawler.py
- pyatlan/model/packages/sigma_crawler.py
- pyatlan/model/packages/snowflake_crawler.py
- pyatlan/model/packages/sql_server_crawler.py
- pyatlan/model/packages/tableau_crawler.py
- tests/unit/data/package_requests/sigma_api_token.json
- tests/unit/data/package_requests/snowflake_basic.json
- tests/unit/data/package_requests/snowflake_keypair.json
- tests/unit/data/package_requests/sql_server_basic.json
- tests/unit/test_packages.py
> DVX-280: Adds `Sigma` and `SQL` server crawler

- .github/workflows/pyatlan-test-cron.yaml
- pyatlan/errors.py
- pyatlan/generator/templates/imports.jinja2
- pyatlan/generator/templates/methods/asset/data_domain.jinja2
- pyatlan/generator/templates/methods/asset/data_product.jinja2
- pyatlan/generator/templates/methods/attribute/data_domain.jinja2
- pyatlan/generator/templates/methods/attribute/data_product.jinja2
- pyatlan/model/assets/asset.py
- pyatlan/model/assets/data_domain.py
- pyatlan/model/assets/data_product.py
- pyatlan/model/data_mesh.py
- pyatlan/model/enums.py
- pyatlan/model/search.py
- tests/integration/.testignore.txt
- tests/integration/data_mesh_test.py
- tests/integration/test_client.py
- tests/unit/data/data_mesh_requests/data_product_assets_dsl.json
- tests/unit/model/constants.py
- tests/unit/model/data_domain_test.py
- tests/unit/model/data_product_test.py
- tests/unit/test_search_model.py
```sh
configfile: tox.ini
plugins: order-1.1.0, sugar-1.0.0, cov-4.0.0
collected 12 items                                                                                                                       
tests/integration/data_mesh_test.py ✓✓✓✓✓✓✓✓✓✓✓✓                                                                          100% ██████████
Results (4.51s):
12 passed
```
> DVX-277 Data mesh updates

- pyatlan/model/packages/__init__.py
- pyatlan/model/packages/base/miner.py
- pyatlan/model/packages/snowflake_miner.py
- tests/unit/data/package_requests/snowflake_miner_default.json
- tests/unit/data/package_requests/snowflake_miner_s3_offline.json
- tests/unit/data/package_requests/snowflake_miner_source.json
- tests/unit/test_packages.py
Docs: https://github.com/atlanhq/atlan-developer-portal/pull/294
> DVX-404: Adds support for `Snowflake Miner`

- pyatlan/client/asset.py
- tests/integration/glossary_test.py
Need to add an additional parameter to allow the specification of attributes to be included in related assets that may be returned by the hierarchy search.
> Initial implementation of DVX-430

- pyatlan/cache/custom_metadata_cache.py
> DVX-553 Error message receiving wrong number of parameters

- pyatlan/model/enums.py
We have added Prefect frontend configs in ETL for connection and process. Extending the functions for python SDK.
> CXD-114 : Add Prefect etl connector in enum

- pyatlan/pkg/utils.py
- Updated `validate_connection()` to include other types.
Tested this change on: https://github.com/atlanhq/marketplace-csa-scripts/blob/main/packages-python/csa-issue-alerter/tests/test-main.py
> DVX-616: Added function to set the workflow headers for custom package

- pyatlan/multipart_data_generator.py
- tests/integration/lineage_test.py
- Fixed Atlan tag image upload multipart form to include `'name="image"'` field.
> DVX-623: Fixed multipart form for Atlan tag image upload

- pyatlan/model/enums.py
Added below new connectors in enums.py
- IICS
- Ab-Initio
- SAP-S4-HANA
> CXD-237 | Added New connectors

- pyatlan/model/enums.py
Added `inriver` new connector in enums.py
> CXD-251 | Added inRiver new connectors

- pyatlan/model/enums.py
Adding new connector to saas, BIGID
> CXD-329 : Adding new connector

- pyatlan/model/enums.py
Added new `dataverse` connector in enums.py
> CXD-304 | Added new `dataverse` connector

- pyatlan/model/enums.py
- pyatlan/model/packages/__init__.py
- pyatlan/model/packages/lineage_builder.py
- pyatlan/model/packages/lineage_generator_nt.py
- tests/unit/data/package_requests/lineage_builder_adls.json
- tests/unit/data/package_requests/lineage_builder_gcs.json
- tests/unit/data/package_requests/lineage_builder_s3.json
- tests/unit/data/package_requests/lineage_generator_default.json
- tests/unit/data/package_requests/lineage_generator_full.json
- tests/unit/test_packages.py
> APP-4603: Added support for `LineageBuilder` and `LineageGenerator` packages

- pyatlan/client/workflow.py
- pyatlan/utils.py
- tests/unit/constants.py
- tests/unit/test_workflow_client.py
> APP-5050: Extended `WorkflowClient.run()` method to accept raw workflow `JSON` (str)

- .github/release.yml
- .github/workflows/build_and_upload_conda_packages.yaml
- .github/workflows/pyatlan-docs.yaml
- .github/workflows/pyatlan-publish.yaml
- .github/workflows/pyatlan-test-cron.yaml
Let's migrate to pinned tags in the future: https://blog.rafaelgss.dev/why-you-should-pin-actions-by-commit-hash
> APP-5260: Updated GH actions to the latest version

- pyatlan/model/enums.py
Introduces 2 new connector types and their corresponding icons
[Frontend PR](https://github.com/atlanhq/atlan-frontend/pull/23806)
> APP-5338 | Add connector types CrateDB and KX

- pyatlan/generator/templates/macros.jinja2
- pyatlan/generator/templates/methods/asset/asset.jinja2
- pyatlan/generator/templates/referenceable_attributes.jinja2
- pyatlan/generator/templates/referenceable_methods.jinja2
- pyatlan/model/assets/core/asset.py
- pyatlan/model/assets/core/referenceable.py
```py
import json
from pyatlan.model import assets
def main():
sql_column = assets.Column.creator(
name="SAMPLE_COLUMN",
parent_qualified_name="default/postgres/1728518400/TEST_DB/TEST_SCHEMA/TEST_TABLE",
parent_type=assets.Table,
order=1,
parent_name="TEST_TABLE",
database_name="TEST_DB",
database_qualified_name="default/postgres/1728518400/TEST_DB",
schema_name="TEST_SCHEMA",
schema_qualified_name="default/postgres/1728518400/TEST_DB/TEST_SCHEMA",
table_name="TEST_TABLE",
table_qualified_name="default/postgres/1728518400/TEST_DB/TEST_SCHEMA/TEST_TABLE",
connection_qualified_name="default/postgres/1728518400",
)
sql_columns_dict = sql_column.dict(by_alias=True, exclude_unset=True)
print(json.dumps(sql_columns_dict, default=str))
main()
```
```json
{
"typeName":"Column",
"attributes":{ …
```
> APP-5676: Remove redundant asset relationship fields

- pyatlan/model/enums.py
Add documentDB connectorType
JIRA - [APP-5912](https://atlanhq.atlassian.net/browse/APP-5912)
[APP-5912]: https://atlanhq.atlassian.net/browse/APP-5912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> APP=5912 | Add documentdb connectorType

- pyatlan/errors.py
- pyatlan/generator/templates/methods/asset/data_product.jinja2
- pyatlan/model/assets/core/data_product.py
- tests/integration/data_mesh_test.py
- tests/unit/model/data_product_test.py
> APP-5956 : Add custom `AtlanError` for the `DataProduct.get_assets` method 

- pyatlan/client/atlan.py
- pyatlan/utils.py
- Migrated from `TLS` to `ContextVars` to support both multithreading and async environments
**Jira link:** _[APP-6156](https://atlanhq.atlassian.net/browse/APP-6156), [APP-6379](https://atlanhq.atlassian.net/browse/APP-6379)_
---
---
---
[APP-6579]: https://atlanhq.atlassian.net/browse/APP-6579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-6379]: https://atlanhq.atlassian.net/browse/APP-6379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[APP-6156]: …
> APP-6156: Migrated from `TLS` to `ContextVars` to support both multithreading and async environments

- pyatlan/generator/templates/methods/asset/atlas_glossary_category.jinja2
- pyatlan/generator/templates/methods/attribute/atlas_glossary_category.jinja2
- pyatlan/generator/templates/methods/attribute/atlas_glossary_term.jinja2
- pyatlan/model/assets/core/atlas_glossary_category.py
- pyatlan/model/assets/core/atlas_glossary_term.py
- tests/integration/glossary_test.py
- tests/unit/model/glossary_category_test.py
- tests/unit/model/glossary_term_test.py
- tests/unit/test_glossary_term.py
**Jira link:** [APP-6571](https://atlanhq.atlassian.net/browse/APP-6571)
---
---
---
[APP-6571]: https://atlanhq.atlassian.net/browse/APP-6571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  APP-6571: Simplified `AtlasGlossaryCategory/Term.creator()` methods

- pyatlan/client/asset.py
- pyatlan/model/audit.py
- pyatlan/model/search_log.py
- tests/unit/test_client.py
**Jira link:** [https://atlanhq.atlassian.net/browse/APP-6766](APP-6766)
---
---
---
> APP-6766: Prevent pagination loop break by filtering invalid assets

- pyatlan/client/asset.py
- tests/unit/test_client.py
Briefly explain the purpose of this PR and what it covers. Mention any related issues or Jira tickets.
https://atlanhq.atlassian.net/browse/APP-6766
---
---
---
- [] I’ve updated the documentation as needed
> APP-6766: Added default `typeName=Referenceable` for must clauses

- pyatlan/client/asset.py
- tests/integration/client.py
- tests/integration/suggestions_test.py
https://atlanhq.atlassian.net/browse/APP-6910
---
---
---
> [test] Fixed `suggestions_test` and added `delete_type` param to `purge_by_guid()` method

- pyatlan/client/asset.py
- tests/integration/glossary_test.py
- tests/integration/persona_test.py
- tests/integration/purpose_test.py
- tests/integration/utils.py
https://atlanhq.atlassian.net/browse/APP-8028
> APP-8028: Fix glossary, persona, purpose tests (using custom retries)

- .conda-envs/build-env.yaml
- .conda-envs/meta.yaml
- .github/workflows/build_and_upload_conda_packages.yaml
- .github/workflows/pyatlan-pr.yaml
- .github/workflows/pyatlan-publish-anaconda.yaml
- also bumped to latest dependencies.
https://atlanhq.atlassian.net/browse/APP-8071
> [fix/ci] Fix conda packages publish GitHub workflow

- .github/workflows/pyatlan-wolfi-base.yaml
- Dockerfile.wolfi
https://atlanhq.atlassian.net/browse/APP-7913
> [ci] Added workflow for `pyatlan-wolfi-base` image build
