atlanhq/atlan-python

- pyatlan/cache/classification_cache.py
- pyatlan/cache/custom_metadata_cache.py
- pyatlan/client/atlan.py
- Forces a cache refresh any time a new custom metadata or classification typedef is created or deleted
- Renames `_refresh_cache` methods within the caches to `refresh_cache`, since they're no longer private
> Refresh caches on any SDK-driven creates or deletes

- pyatlan/client/atlan.py
- pyatlan/events/atlan_event_handler.py
- tests/integration/connection_test.py
- tests/integration/custom_metadata_test.py
- tests/integration/file_test.py
- tests/integration/glossary_test.py
- tests/integration/lineage_test.py
- tests/integration/persona_test.py
- tests/integration/purpose_test.py
- tests/integration/s3_asset_test.py
- tests/integration/test_client.py
- tests/integration/test_sql_assets.py
- tests/unit/test_client.py
- tests/unit/test_search_model.py
- Adds new `update_merging_cm()` and `update_replacing_cm()` operations that strictly update (do not create)
- Renames various `upsert_...()` operations to `save_...()` (including `upsert()` -> `save()`), for two reasons:
1. Clarity between `upsert` and `update` operations (above) in quickly reading code
2. Consistency across SDKs
Also took the opportunity to consolidate duplicate code across the various `upsert...()` methods by instead calling each other.
(And added documentation to each of these methods to explain what they do directly in-IDE.)
> Adds a creation-only semantic operation, and renames upsert to save

- pyatlan/client/atlan.py
This is not possible programmatically with an API token any longer (for security reasons), so these operations are no longer valid for the SDK.
> Removes ability to activate and deactivate users

- pyatlan/logging.conf
- pyatlan/utils.py
```
2023-11-22 15:19:32,329 - pyatlan.client.atlan - DEBUG - {'totalRecord': 5, 'filterRecord': 1, 'records': [{'alias': 'Admins', 'attributes': {'alias': ['Admins'], 'createdAt': ['1691010302538'], 'createdBy': ['<hidden>'], 'isDefault': ['true'], 'updatedAt': ['1691016077625'], 'updatedBy': ['chris']}, 'id': '<hidden>', 'name': 'admins', 'path': '/admins', 'personas': [{'id': '<hidden>', 'name': 'Business Definitions', 'displayName': 'Business Definitions', 'qualifiedName': '<hidden>'}, {'id': '<hidden>', 'name': 'Data Assets', 'displayName': 'Data Assets', 'qualifiedName': '<hidden>'}], 'purposes': [{'guid': '<hidden>', 'name': 'Known Issues', 'qualifiedName': '<hidden>'}], 'userCount': 8}]}
```
```
2023-11-22 15:16:47,514 - pyatlan.client.atlan - DEBUG - {"totalRecord": 5, …
```
> DVX-51: Add JSON formatter to the logger

- pyatlan/client/atlan.py
- pyatlan/client/constants.py
- pyatlan/client/search_log.py
- pyatlan/model/enums.py
- pyatlan/model/search.py
- pyatlan/model/search_log.py
- tests/integration/client.py
- tests/integration/test_client.py
- tests/unit/data/search_log_responses/sl_detailed_log_entries.json
- tests/unit/data/search_log_responses/sl_most_recent_viewers.json
- tests/unit/data/search_log_responses/sl_most_viewed_assets.json
- tests/unit/test_client.py
- tests/unit/test_search_model.py
```py
from pyatlan.model.search_log import SearchLogRequest
request = SearchLogRequest.by_guid(
guid="<asset-guid>", user_size=2
)
response = client.search_log.search(request)
print(f"Total Assets Views : {response.total_views}")
for user in response.unique_users:
print(
f"Username : {user.name}, View count: {user.view_count}, Last view timestamp : {user.view_timestamp}"
)
```
```bash
Total Assets Views : 39
Username : aryaman.bhushan, View count: 37, Last view timestamp : 2023-12-05 11:27:56.977000+00:00
Username : chris, View count: 2, Last view timestamp : 2023-12-05 09:52:46.723000+00:00
```
```py
request = SearchLogRequest.by_guid(
guid="<asset-guid>",
user_size=2,
start_time=1701766262000, …
```
> DVX-48: Add support for search log access

- pyatlan/client/workflow.py
The `WorkflowResponse` **metadata.name** provides the name of the workflow. Therefore, when calling 
`/api/service/runs/indexsearch`, we should find the latest workflow run by passing its name it's name to `spec.workflowTemplateRef.name.keyword` to obtain the desired results.
> Fixes workflow client `monitor` method

- pyatlan/client/atlan.py
- pyatlan/client/constants.py
- pyatlan/client/credential.py
- pyatlan/errors.py
- pyatlan/model/credential.py
- pyatlan/model/packages/base/crawler.py
- pyatlan/model/packages/base/package.py
- pyatlan/model/packages/confluent_kafka_crawler.py
- pyatlan/model/packages/dbt_crawler.py
- pyatlan/model/packages/glue_crawler.py
- pyatlan/model/packages/powerbi_crawler.py
- pyatlan/model/packages/snowflake_crawler.py
- pyatlan/model/packages/tableau_crawler.py
- tests/unit/data/package_requests/dbt_cloud.json
- tests/unit/data/package_requests/glue_iam_user.json
- tests/unit/data/package_requests/powerbi_delegated_user.json
- tests/unit/data/package_requests/powerbi_service_principal.json
- tests/unit/data/package_requests/snowflake_basic.json
- tests/unit/data/package_requests/snowflake_keypair.json
- tests/unit/data/package_requests/tableau_access_token.json
- tests/unit/data/package_requests/tableau_basic.json
- tests/unit/test_credential_client.py
- tests/unit/test_packages.py
```py
import logging
from pyatlan.model.credential import Credential
logging.basicConfig(level=logging.DEBUG)
snowflake_cred = client.credential.get(guid="<cred-guid-123>").to_credential()
snowflake_cred.auth_type = "basic"
snowflake_cred.username = "<user>"
snowflake_cred.password = "<pass>"
snowflake_cred.extras = {
"role": "<role>",
"warehouse": "<wh>",
}
snowflake_cred.auth_type = "keypair"
snowflake_cred.username = "<user>"
snowflake_cred.password = KEY
snowflake_cred.extras = {
"role": "<role>",
"warehouse": "<wh>",
"private_key_password": "<pass>",
}
response = client.credential.test_and_update(credential=snowflake_cred)
```
> DVX-97: Adds credential management and refactor packages

- pyatlan/client/atlan.py
- pyatlan/client/credential.py
- tests/unit/test_credential_client.py
- Fixes invalid GUID credential retrieval.
> Change atlan credential client property name to "credentials" similar to the Java SDK

- pyatlan/generator/templates/imports.jinja2
- pyatlan/generator/templates/methods/asset/a_d_l_s_object.jinja2
- pyatlan/generator/templates/methods/attribute/a_d_l_s_object.jinja2
- pyatlan/model/assets/asset61.py
- pyatlan/utils.py
- tests/integration/adls_asset_test.py
- tests/unit/model/a_d_l_s_object_test.py
I believe we can extract the `ADLS account` qualified name directly from `adls_container_qualified_name` within the `create()` method, following a similar approach to what we're doing in the [Java SDK](https://github.com/atlanhq/atlan-java/blob/0be79dd4061a9573845ce5b637e8e93939a13088/sdk/src/main/java/com/atlan/model/assets/ADLSObject.java#L500).
> DVX-130: Fixes setup of the `ADLSObject` asset

- pyatlan/client/asset.py
- pyatlan/errors.py
- tests/integration/test_client.py
- tests/unit/test_client.py
- tests/unit/test_credential_client.py
- tests/unit/test_typedef_model.py
**Note:** Initially, I attempted to implement this functionality using third-party packages, such as [multimethod](https://github.com/coady/multimethod), which offer method overloading. [Despite Python not natively supporting](https://stackoverflow.com/a/10202988) method overloading like some other languages, I encountered issues with type hints and significant code duplication. Therefore, I opted for achieving a similar outcome using default values and the `*args` and `**kwargs` syntax.
> DVX-131: Add ability to update certificate, announcement for GlossaryTerm and GlossaryCategory

- .github/workflows/pytest.yaml
- qa-checks
- tox.ini
**Sample QA checks outputs:**
- Failure: https://github.com/atlanhq/atlan-python/actions/runs/7583173483/job/20654254675?pr=224#step:5:1
- Success: https://github.com/atlanhq/atlan-python/actions/runs/7583235841/job/20654435937?pr=224#step:5:1
> DVX-181: Adds QA checks (black, flake8, mypy) to the CI

- .github/workflows/pyatlan-pr.yaml
- Added [`concurrency`](https://docs.github.com/en/actions/using-jobs/using-concurrency) to the parallel integration tests. It will put workflow jobs in a waiting state if a similar integration test is already running in a workflow.
> Fixes parallel testing concurrency

- .github/workflows/pyatlan-pr.yaml
- .github/workflows/pyatlan-test-cron.yaml
- requirements-dev.txt
- tox.ini
- Integrate the [pytest-sugar ](https://github.com/Teemu/pytest-sugar)plugin, which enhances pytest functionality by instantly showing failures and errors, adding a progress bar, improving test results, and enhancing the overall output appearance.
- Utilize the [pytest-timer](https://github.com/skudriashev/pytest-timer) plugin to display the durations of the 'n' slowest tests. This feature can be **DISABLED** by default and can be used in our CI.
Adjust pytest configuration settings to ignore `DeprecationWarning` messages, improving test report clarity.
**Before:**
- Failure: https://github.com/atlanhq/atlan-python/actions/runs/8001762037/job/21853667577#step:5:108
- Pass: https://github.com/atlanhq/atlan-python/actions/runs/8009305871/job/21877738515?pr=251#step:5:36
**After:**
- …
> DVX-272: Enhance pyatlan tests report experience

- pyatlan/model/enums.py
Customer IFF is looking to ingest their factory IoT metadata as relational catalogs on Atlan. Changes are for integrating the connectors involved.
> Adding AWS IoT connectors

- pyatlan/utils.py
The problem was the code used to flatten structs was assuming the value in attributes for the struct_name always contained a list and `mcMonitorRuleScheduleConfig` contain a dict with the typeName and attributes.
> Fix DVX-352 Attempting to retrieve an MC Monitor asset by GUID is failing in field-sandbox

- pyatlan/client/asset.py
- pyatlan/client/atlan.py
- pyatlan/model/core.py
- tests/unit/test_deprecated.py
- We previously assumed lineage-only propagation was added using `propagation_only_through_lineage`, but it's actually released with `restrict_propagation_through_hierarchy`.
- More info: https://atlanhq.atlassian.net/browse/PLT-1092
>  DVX-366: Add support for `restrict_propagation_through_hierarchy` in the `AtlanTag`

- pyatlan/model/core.py
~Also updated the parameter name in tag methods from `restrict_propagation_through_hierarchy` to `restrict_hierarchy_propagation` for consistency with other parameters.~
> Fixes field alias typo for `restrict_propagation_through_hierarchy` in the `AtlanTag` model.

- pyatlan/model/enums.py
```py
from pyatlan.model.assets import Persona
from pyatlan.model.enums import AssetSidebarTab, AssetFilter
to_update = Persona.create_for_modification(
"default/Ng5X6AXv8Tcz2eyKkS3bIh", "Test-Persona", True
)
to_update.deny_asset_tabs = {
AssetSidebarTab.LINEAGE.value,
AssetSidebarTab.RELATIONS.value,
AssetSidebarTab.QUERIES.value,
}
to_update.deny_asset_types = {"Table", "Column"}
to_update.deny_asset_filters = {
AssetFilter.OWNERS.value,
AssetFilter.TAGS.value,
AssetFilter.CERTIFICATE.value,
}
to_update.deny_custom_metadata_guids = {
"59220d25-5d39-4f3a-8de5-072098bee793",
"bb0c9836-94fd-4a54-9007-0f25fb802c2c",
}
response = client.asset.save(to_update)
print(response)
```
> DVX-362: Adds `AssetFilter` enum

- pyatlan/generator/templates/macros.jinja2
- pyatlan/model/assets/atlas_glossary_category.py
- pyatlan/model/assets/data_product.py
- pyatlan/model/assets/looker_project.py
- pyatlan/model/enums.py
- tests/integration/glossary_test.py
- tests/unit/model/glossary_category_test.py
- Retrieved latest `DataProduct` model changes.
- Renamed enum `AssetFilter` -> `AssetFilterGroup`.
> DVX-379: Fixes logic for removing parent category relationship in `AtlasGlossaryCategory`

- pyatlan/client/asset.py
- pyatlan/generator/templates/methods/asset/atlas_glossary.jinja2
- pyatlan/generator/templates/methods/asset/atlas_glossary_category.jinja2
- pyatlan/generator/templates/methods/asset/atlas_glossary_term.jinja2
- pyatlan/model/assets/atlas_glossary.py
- pyatlan/model/assets/atlas_glossary_category.py
- pyatlan/model/assets/atlas_glossary_term.py
- tests/integration/glossary_test.py
- tests/unit/data/search_responses/glossary_category_by_name.json
- tests/unit/test_client.py
- Also added `relation_attributes=['name']` to the `IndexSearchRequest` to include the related asset name.
>  DVX-387: Corrects `qualified_name` population for related entities in glossary objects

- pyatlan/model/core.py
- tests/integration/lineage_test.py
- tests/integration/test_client.py
- tests/unit/test_client.py
- Also fixes issues with multiple remove/append relationships
Previously, values were being overwritten inside append/remove dictionaries.
```py
term1.attributes.see_also = [
AtlasGlossaryTerm.ref_by_guid(guid=term2.guid),
AtlasGlossaryTerm.ref_by_guid(
guid=term3.guid, semantic=SaveSemantic.APPEND
),
]
term1.attributes.preferred_to_terms = [
AtlasGlossaryTerm.ref_by_guid(
guid=term3.guid, semantic=SaveSemantic.APPEND
),
]
```
>   DVX-392: Fixes explicit assignment of `None` to asset attributes in `BulkRequest`

- pyatlan/client/atlan.py
- pyatlan/client/constants.py
- pyatlan/client/sso.py
- pyatlan/errors.py
- pyatlan/model/enums.py
- pyatlan/model/sso.py
- tests/integration/test_sso_client.py
- tests/unit/data/sso_responses/create_group_mapping.json
- tests/unit/data/sso_responses/get_all_group_mapping.json
- tests/unit/data/sso_responses/get_group_mapping.json
- tests/unit/data/sso_responses/update_group_mapping.json
- tests/unit/test_sso_client.py
```py
group = client.group.get_by_name("test-group-2")[0]
response = client.sso.get_all_group_mappings(sso_alias="auth0")
response = client.sso.create_group_mapping(
sso_alias="auth0",
atlan_group=group,
sso_group_name="sso_create_1234",
)
group_map_id = "0637576a-5419-40d7-b6cb-fe5841b1da4b"
response = client.sso.get_group_mapping(
sso_alias="auth0",
group_map_id=group_map_id,
)
response = client.sso.update_group_mapping(
sso_alias="auth0",
atlan_group=group,
group_map_id=group_map_id,
sso_group_name="sso_update_1234",
)
response = client.sso.delete_group_mapping(sso_alias="auth0", group_map_id=group_map_id)
```
> DVX-377: Adds support for SSO grouping

- pyatlan/client/file.py
- pyatlan/model/file.py
- tests/integration/test_client.py
- tests/integration/test_file_client.py
- tests/integration/test_index_search.py
- tests/unit/constants.py
- tests/unit/test_file_client.py
- Moved presigned URL cloud detection logic directly to the `FileClient.upload_file()` method.
https://github.com/atlanhq/atlan-developer-portal/pull/288#discussion_r1583436547
> req-changes: Use string presigned URL

- docs/requirements.txt
- pyatlan/client/constants.py
- pyatlan/client/workflow.py
- pyatlan/model/workflow.py
- requirements.txt
- tests/integration/test_client.py
- tests/integration/test_workflow_client.py
- tests/unit/constants.py
- tests/unit/test_workflow_client.py
This PR adds the following methods to the `WorkflowClient`:
- `run()` (now with `workflow_schedule`)
- `get_runs()` (to retrieve existing workflow runs)
- `add_schedule()` (to add a schedule to a workflow)
- `remove_schedule()` (to remove a schedule from a workflow)
- `get_schedule()` (to retrieve a specific schedule by workflow name)
- `get_all_schedules()` (to retrieve all scheduled workflows)
- `delete()` (to archive (delete) the provided workflow)
- `stop()` (to stop the provided running workflow).
Adds integration and unit tests for `WorkflowClient`.
Merged `dependabot` PRs.
> DVX-405: Adds support for scheduling workflow runs

- pyatlan/generator/class_generator.py
- pyatlan/generator/templates/module.jinja2
When a new `atlas_core` enum is introduced and generated models depend on those enums, a `NameError` occurs due to the hardcoding of [enums in the template](https://github.com/atlanhq/atlan-python/blob/main/pyatlan/generator/templates/imports.jinja2#L18). This issue arises because the hardcoded enums are not up-to-date with the latest enums. To address this problem, I inject the atlas enums directly into the template. However, I retain the hardcoded enums import statement in the template, as it contains all enums (both `pyatlan` defined and `generated enums`). After generation, pre-commit formatting checks are used to clean up any duplicate or unused import statements.
> DVX-432: Utilize generated `atlas core` enums in the template

- pyatlan/model/packages/dynamo_d_b_crawler.py
- pyatlan/model/packages/postgres_crawler.py
- tests/unit/test_packages.py
I found this while working on: https://github.com/atlanhq/atlan-developer-portal/pull/301. This will result in a [breaking change](https://github.com/atlanhq/atlan-python/pull/327). Moving forward, I'll aim to merge docs PRs first and then cut the release here to prevent such issues in the future.
> Fixes typo in `IAM` role methods of `DynamoDB` and `PostgreSQL` crawlers

- pyatlan/errors.py
- pyatlan/generator/templates/imports.jinja2
- pyatlan/generator/templates/methods/asset/data_contract.jinja2
- pyatlan/generator/templates/methods/attribute/data_contract.jinja2
- pyatlan/model/assets/data_contract.py
- tests/integration/data_mesh_test.py
- tests/unit/model/constants.py
- tests/unit/model/data_contract_test.py
- Updated `creator()` to use the **Atlan CLI** approach to construct the `DataContract` **name**.
```py
from json import dumps
from pyatlan.model.assets import DataContract
from pyatlan.model.enums import CertificateStatus
contract_json = {
"type": table.type_name,
"status": CertificateStatus.DRAFT,
"kind": "DataContract",
"data_source": connection.name,
"dataset": table.name,
"description": "Automated testing of the Python SDK.",
}
contract = DataContract.creator(
asset_qualified_name=table.qualified_name,
contract_json=dumps(contract_json),
)
response = client.asset.save(contract)
```
> DVX-398: Removed the required kwarg (`name`) from the `DataContract` `creator()`

- pyatlan/client/asset.py
- pyatlan/errors.py
- pyatlan/model/fluent_search.py
- tests/integration/test_index_search.py
- tests/unit/data/search_responses/index_search_paging.json
- tests/unit/test_client.py
The feature implements a new pagination approach for search, known as `bulk` search, based on asset creation timestamps. This approach is used when the number of results exceeds the predefined threshold (i.e: `100,000` assets). Users can explicitly run this search by setting the optional keyword argument `bulk=True` in the `FluentSearch.execute()` or `asset.search()` methods.
```py
results = (
FluentSearch()
.where(CompoundQuery.active_assets())
.where(CompoundQuery.asset_type(AtlasGlossaryTerm))
.page_size(2)
).execute(client, bulk=True)
request = (
FluentSearch()
.where(CompoundQuery.active_assets())
.where(CompoundQuery.asset_type(AtlasGlossaryTerm))
.page_size(2)
).to_request()
results = client.asset.search(criteria=request, bulk=True)
````
> DVX-488: Implement infinite paging approach

- .github/workflows/pyatlan-pr.yaml
- pyatlan/model/aggregation.py
- pyatlan/model/suggestions.py
- tests/integration/conftest.py
- tests/integration/suggestions_test.py
- tests/integration/test_index_search.py
```py
from pyatlan.model.suggestions import Suggestions
table = client.asset.get_by_guid("ccd78e6b-6648-40e3-847f-e0d6412e8fc9")
response = (
Suggestions(includes=Suggestions.TYPE.all())
.finder(table)
.apply(allow_multiple=True)
)
print(response)
response = Suggestions(includes=Suggestions.TYPE.all()).finder(table).get()
print(response)
```
> DVX-453: Added support for `trident` suggestions

- .github/workflows/pyatlan-test-cron.yaml
- this change will improve test results readability in the [GH actions.](https://github.com/atlanhq/atlan-python/actions/runs/10051075019/job/27780049060)
> ci: Removed `pytest-sugar` plugin from test cron

- pyatlan/generator/templates/methods/attribute/readme.jinja2
- pyatlan/model/assets/core/readme.py
- tests/unit/model/readme_test.py
- tests/unit/test_model.py
This prevents users from updating a `README` `relationshipGuid` where the `relationshipStatus` is `DELETED` (when the asset `GUID` is absent). This restriction ensures users must use `ref_by_guid` rather than `ref_by_qualified_name`, ensuring that a new `README` is created instead of updating an existing one.
> DVX-579: Ensure the asset to which the `README` is attached has a `GUID`

- pyatlan/client/atlan.py
- pyatlan/client/common.py
- pyatlan/client/constants.py
- pyatlan/client/open_lineage.py
- pyatlan/errors.py
- pyatlan/model/enums.py
- pyatlan/model/open_lineage/__init__.py
- pyatlan/model/open_lineage/base.py
- pyatlan/model/open_lineage/column_lineage_dataset.py
- pyatlan/model/open_lineage/dataset.py
- pyatlan/model/open_lineage/event.py
- pyatlan/model/open_lineage/facet.py
- pyatlan/model/open_lineage/input_dataset.py
- pyatlan/model/open_lineage/job.py
- pyatlan/model/open_lineage/output_dataset.py
- pyatlan/model/open_lineage/run.py
- pyatlan/model/open_lineage/utils.py
- pyatlan/utils.py
- requirements.txt
- tests/unit/data/open_lineage_requests/event_complete.json
- tests/unit/data/open_lineage_requests/event_start.json
- tests/unit/model/open_lineage/open_lineage_test.py
```py
from pyatlan.model.enums import OpenLineageEventType
from pyatlan.model.open_lineage.event import OpenLineageEvent
from pyatlan.model.open_lineage.job import OpenLineageJob
from pyatlan.model.open_lineage.run import OpenLineageRun
namespace = "snowflake://abc123.snowflakecomputing.com"
producer = "https://your.orchestrator/unique/id/123"
job = OpenLineageJob.creator(
connection_name="test-2", job_name="dag_123", producer=producer
)
run = OpenLineageRun.creator(job=job)
id = job.create_input(namespace=namespace, asset_name="OPS.DEFAULT.RUN_STATS")
od = job.create_output(namespace=namespace, asset_name="OPS.DEFAULT.FULL_STATS")
od.to_fields = [
{
"COLUMN": [
id.from_field(field_name="COLUMN"), …
```
> DVX-522: Added initial support for sending `OpenLineage` events 

- tests/integration/test_sql_assets.py
- Added delay to ensure the column is properly indexed; otherwise, the generated spec may return empty (`columns: []`).
> DVX-701: Fixed test_sql_assets: Ensured `Readme` asset is passed by `ref_by_guid()`

- pyatlan/client/constants.py
- pyatlan/client/credential.py
- pyatlan/model/credential.py
- tests/integration/test_workflow_client.py
- tests/unit/test_credential_client.py
Made the following changes:
1. Add a method called **`get_all()`** 
2. Defined a new model called **`CredentialResponseList`**
3. Added a new constant called **`GET_ALL_CREDENTIALS`**
> FT-778: Add credential list endpoint to the SDKs

- pyatlan/client/asset.py
>  It’s currently possible to hit an edge case where e.g. the total number of results is 9932, but because we page by default at 300 per page we end up sending a request from offset 9900 with a size of 300 <— in total this would take us above the 10000 threshold (to 10200) <— which Elastic will throw an error on.
We should ensure that we properly mitigate this edge case.
Remove possibility of overrunning search pages when total results are just under the threshold:
- DEFAULT_PAGE_SIZE = 300
- _MASS_EXTRACT_THRESHOLD = 100000 - DEFAULT_PAGE_SIZE
> FT-790: Remove possibility of overrunning search pages when total results are just under the threshold

- pyatlan/client/asset.py
- pyatlan/model/audit.py
- tests/integration/test_index_search.py
- Timestamp paging returns incomplete results when running search with small page size and assets have duplicate creation times
> FT-865: Fixed timestamp paging returns incomplete results

- pyatlan/client/search_log.py
- pyatlan/errors.py
- pyatlan/model/search_log.py
- tests/integration/test_client.py
- tests/unit/data/search_responses/search_log_search_paging.json
- tests/unit/test_search_log_search.py
Implementing a query rewrite for a time-based pagination approach for search, known as bulk search, based on asset creation timestamps. This approach is used when the number of results exceeds the predefined threshold (i.e: 10,000 assets). Users can explicitly run this search by setting the optional keyword argument bulk=True in the  search_log.search() methods.
> FT-853: Implement query rewrite for Searchlog responses

- pyatlan/client/atlan.py
https://atlanhq.atlassian.net/browse/FT-821?focusedCommentId=312475
>  FT-842: Enabled the use of `Retry-After` header value for handling rate-limit retries

- pyatlan/model/assets/s3_object.py
- tests/integration/s3_asset_test.py
- tests/unit/model/s3object_test.py
- Added `s3_bucket_name` parameter in S3Object.create() method
- Added `s3_bucket_name` parameter in S3Object.create_with_prefix() method
> FT-892: Ensure create_with_prefix sets the s3BucketName attribute

- pyatlan/model/core.py
- tests/unit/test_atlan_tag_name.py
- Fixed [an issue](https://github.com/atlanhq/atlan-python/actions/runs/12828063637/job/35771490721?pr=479#logs) where deserialization of `Purpose` assets failed with a `ValueError` when encountering deleted or non-existent `AtlanTagName` in the `purposeClassifications` attribute.
- Updated logic to replace invalid or deleted tags with a sentinel object instead of raising a `ValueError`, ensuring smoother deserialization.
Error example:
```py
__root__ -> 9 -> detail -> attributes -> purposeClassifications -> 0
zXjPUQ4QJQwukO6KuWmZZA is not a valid AtlanTag (type=value_error).
Suggestion: Atlan was unable to produce a valid response to your request.
Please verify your request is valid.
```
This fix improves the resilience of the deserialization process by providing a fallback for invalid …
> APP-4781 | Handled deleted `AtlanTagName` gracefully in `Purpose` asset deserialization

- pyatlan/client/atlan.py
As discussed, for valid cases in the lineage listing API that may take longer, we've decided to increase the default `read` timeout of the client to 15 minutes.
> APP-5054: Increased default read timeout to `15` minutes for `AtlanClient`

- .github/workflows/pyatlan-pr.yaml
- pyatlan/cache/abstract_asset_cache.py
- pyatlan/client/open_lineage.py
- pyatlan/client/workflow.py
- pyatlan/model/fields/atlan_fields.py
- setup.py
- tests/integration/test_file_client.py
- tests/unit/test_audit_search.py
- tests/unit/test_client.py
- tests/unit/test_search_log_search.py
- tests/unit/test_search_model.py
- tests/unit/test_workflow_client.py
- Updated the code to use `enum.value` instead of `enum`.
In Python versions < `3.12`, `enum` was implicitly converted to `enum.value` during string test assertions. However, in Python >= `3.12`, this implicit conversion no longer occurs, causing unit test failures. To ensure consistency, we should explicitly use `enum.value` when raising any `AtlanError`.
- Expanded the Python version matrix in the Pyatlan PR CI to include `[3.8, 3.9, 3.10, 3.11, 3.12, 3.13]` for unit testing.
> APP-4749: Added support for Python `3.12` and `3.13.1` (latest)

- pyatlan/client/atlan.py
- tests/integration/test_client.py
- Add delay after token refresh to avoid empty typedef responses.
- Reset `has_retried` if last retry wasn't a `401` to allow future retries.
> APP-6218: Improve 401 token refresh handling

- pyatlan/client/credential.py
For all workflows provided by **Atlan**, the naming convention follows this pattern:
- **Workflow Name:**  
Example:  
```
atlan-bigquery-1735837155
```
- **Credential Name Pattern:**  
```
default-<connector-name>-<timestamp>-0
```  
So for the example above, the credential name would be:  
```
default-bigquery-1735837155-0
```
---
For **CSA packages** using credentials, the format is slightly different:
- **Credential Name Pattern:**  
```
<workflow-name>-0
```
Did local testing as well  ✅  : 
Testing with Atlan connecter:  
Cross check the creds here: https://field-sandbox.atlan.com/workflows/profile/atlan-bigquery-1735837155/config
Testing with csa connector:
Cross check the creds here : https://field-sandbox.atlan.com/workflows/profile/csa-s3-1734926030/config
> APP-5915 : Add "Workflow Name" as an optional param in credentials.get_all()

- pyatlan/generator/templates/methods/asset/document_d_b_collection.jinja2
- pyatlan/generator/templates/methods/asset/document_d_b_database.jinja2
- pyatlan/generator/templates/methods/attribute/document_d_b_collection.jinja2
- pyatlan/generator/templates/methods/attribute/document_d_b_database.jinja2
Fixed the new line issue in template because of which the generator python script was giving indentation error
> fix the indentation issue in documentDB jinja template

- pyatlan/model/fluent_search.py
Tested on `field-sandbox`:
```py
import logging
from pyatlan.model.fluent_search import CompoundQuery, FluentSearch
logging.basicConfig(level=logging.WARN)
client = AtlanClient()  #
request = (
FluentSearch()
.select()  #
.where(
CompoundQuery.tagged_with_value(  #
"Confidential",  #
"Highly Restricted",  #
True,  #
source_tag_qualified_name="default/snowflake/1711669993/ANALYTICS/PRODUCTION/CONFIDENTIAL"
)
)
).to_request()  #
response = client.asset.search(request)
print(response.count)
```
> APP-5774 : Extend tagged with value search with option for specific source tag 

- pyatlan/client/atlan.py
```
ghcr.io/atlanhq/marketplace-csa-scripts-main:latest,ghcr.io/atlanhq/marketplace-csa-scripts-main:a51530e
```
Done with testing - both workflows succeeded using the new `AtlanClient.init_for_thread(client)` method. I’ll release the changes tomorrow! ✅ 
https://fieldtec42.atlan.com/workflows/profile/csa-metadata-completeness-1743083803/runs?name=csa-metadata-completeness-1743083803-62tkd
> APP-6379: Add public method `init_for_thread()` to prepare `AtlanClient` for use in multithreaded envs

- pyatlan/cache/connection_cache.py
- pyatlan/model/enums.py
- pyatlan/utils.py
- tests/integration/connection_test.py
- tests/unit/model/a_d_l_s_object_test.py
- tests/unit/model/connection_test.py
- tests/unit/test_utils.py
Added support for dynamic extension of `AtlanConnectorType` for custom connectors
- Enabled adding custom connector types at runtime
- Ensured compatibility with string behavior and existing enum usage
- Added helper methods to list names and values
```py
import logging
from pyatlan.model.assets import Connection
from pyatlan.model.enums import AtlanConnectionCategory, AtlanConnectorType
logging.basicConfig(level=logging.DEBUG)
AtlanConnectorType.CREATE_CUSTOM(
name="FOO", value="bar", category=AtlanConnectionCategory.API
)
admin_role_guid = client.role_cache.get_id_for_name("$admin")
connection = Connection.creator(
name="test-custom",
connector_type=AtlanConnectorType.FOO,
admin_roles=[admin_role_guid],
)
response = …
```
> APP-6565: Added support for dynamic extension of `AtlanConnectorType` for custom connectors

- pyatlan/client/asset.py
- tests/integration/test_client.py
Since modification of an asset while iterating thru the results of a fluent search make cause the paging to changing and thus assets could be missed provide a method that will ensure that all the assets returned by the search are processed once.
**Jira link:** _[APP-6827](https://atlanhq.atlassian.net/browse/APP-6827)_
---
---
Integration test added.
---
[APP-6827]: https://atlanhq.atlassian.net/browse/APP-6827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> APP-6827 Add utility method to facilitate processing assets while iterating thru results of a fluent search.

- pyatlan/model/enums.py
Adding a missing Primitive Type in AtlanCustomAttributePrimitiveType class of Pyatlan
**Jira link:** _https://atlanhq.atlassian.net/browse/APP-7103_
---
---
---
> APP-7103 : Add Long as a Primitive Type in AtlanCustomAttributePrimitiveType

- pyatlan/client/asset.py
https://atlanhq.atlassian.net/browse/APP-7132
---
---
---
> APP-7132: Fixed FS `search` criteria used for `get_by_qualified_name/guid` method to include asset `type_name`

- pyatlan/model/typedef.py
- tests/unit/test_typedef_model.py
The intended flow involves first creating an enum using PyAtlan, followed by defining a custom metadata type and linking the created enum to one of its AttributeDef fields during the metadata creation process.
However, during this setup, the customer was explicitly setting:
`attr_def.options.multi_value_select = False
`
Even though this was meant to enforce a single-select behavior, setting this property manually led to unintended consequences. The SDK logic did not validate the value of the attribute before applying it, which resulted in:
type_name = "array[]" with cardinality = SET
This configuration contradicts how single-select enums are expected to behave.
As a result, when the customer attempted to assign this custom metadata to an asset, the following error was triggered: …
> APP-7697 : custom metadata object created via Python

- pyatlan/model/constants.py
- pyatlan/model/typedef.py
- tests/unit/constants.py
- tests/unit/test_typedef_model.py
https://atlanhq.atlassian.net/browse/APP-7827
---
---
---
> APP-7827: Added support for `AttributeDef.Options.applicable_ai_asset_types`

- pyatlan/model/translators.py
- tests/unit/test_atlan_tag_name.py
https://atlanhq.atlassian.net/browse/APP-7889
---
---
> APP-7889: Fixed handling of `source_tag` when no attributes present

- pyatlan/client/aio/workflow.py
- pyatlan/model/aio/workflow.py
- tests/integration/aio/test_workflow_client.py
Fix Fix problem in async iterator in AsyncWorkflowSearchResponse
**Jira link:** _[APP-8346](https://atlanhq.atlassian.net/browse/APP-8346)_
---
---
- Added additional check in integration test
---
- [ X] My code follows the project’s style guidelines
- [ x] I’ve performed a self-review of my code
- [ X] I’ve added tests to cover my changes
- [ x] All new and existing tests pass locally
[APP-8346]: https://atlanhq.atlassian.net/browse/APP-8346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> APP-8346 Fix problem in async iterator in AsyncWorkflowSearchResponse

- pyatlan/model/enums.py
- tests/integration/connection_test.py
- tests/unit/test_utils.py
- Force lowering case the value when creating custom connector names
- Added unit tests. 
- Tested below code  :
```
from pyatlan.model.assets import Connection
from pyatlan.model.enums import AtlanConnectionCategory, AtlanConnectorType
import logging
a = AtlanConnectorType.CREATE_CUSTOM(
name="CUSTOM123", value="My_lower_customa", category=AtlanConnectionCategory.CUSTOM
)
print(a)
admin_role_guid = client.role_cache.get_id_for_name("$admin")
connection = Connection.creator(
client=client,
name="test-final",
connector_type=AtlanConnectorType.CUSTOM123,  #
admin_roles=[admin_role_guid],
)
response = client.asset.save(connection)
connection = Connection.creator(
client=client,
name="test-final2", …
```
> APP-8799 : Force-lowercase all connector names
